# Generated by Django 5.1.2 on 2024-10-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addProduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='reviews',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
