# Generated by Django 5.1.1 on 2024-10-26 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addProduct', '__first__'),
        ('autentifikasi', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('liked_foods', models.ManyToManyField(blank=True, to='addProduct.food')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='autentifikasi.profile')),
            ],
        ),
    ]
