# Generated by Django 5.1.1 on 2024-10-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='liked_foods',
            field=models.ManyToManyField(blank=True, to='main.food'),
        ),
    ]
