# Generated by Django 5.1.2 on 2024-10-22 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addProduct', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='review',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addProduct.food'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
