# Generated by Django 5.1.2 on 2024-10-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailMakananfix', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
