# Generated by Django 5.1.2 on 2024-10-27 04:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentifikasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(blank=True, default='https://tse3.mm.bing.net/th?id=OIP.lLmJV7N4bgAwEBtziWijSQHaJL&pid=Api&P=0&h=180', max_length=500, null=True),
        ),
    ]
